In [1]:
import matplotlib.pyplot as plt
import numpy as np

from qutip import * 
import os

# Matplotlib Einstellungen gemäß den LaTeX-Caption-Formatierungen
plt.rcParams.update({
    'text.usetex': True,              # Enable LaTeX for text rendering
    'font.family': 'serif',           # Use a serif font family
    'font.serif': 'Palatino',         # Set Palatino as the serif font
    'text.latex.preamble': r'\usepackage{amsmath}',
    'font.size': 20,                   # Font size for general text
    'axes.titlesize': 20,              # Font size for axis titles
    'axes.labelsize': 20,              # Font size for axis labels
    'xtick.labelsize': 20,             # Font size for x-axis tick labels
    'ytick.labelsize': 20,             # Font size for y-axis tick labels
    'legend.fontsize': 20,             # Font size for legends
    'figure.figsize': [8, 6],          # Size of the plot (width x height)
    'figure.autolayout': True,         # Automatic layout adjustment
    'savefig.format': 'svg',           # Default format for saving figures
    'figure.facecolor': 'none',        # Make the figure face color transparent
    'axes.facecolor': 'none',          # Make the axes face color transparent
    'savefig.transparent': True        # Save figures with transparent background
})

output_dir = r"C:\Users\leopo\OneDrive - UT Cloud\Uni\Semester_9\Master_thesis\Figures_From_Python"
os.makedirs(output_dir, exist_ok=True)

$$
H = E \left|1\right\rangle \left\langle 1\right| + \Omega\left(\left|0\right\rangle \left\langle 1\right| + \left|1\right\rangle \left\langle 0\right|\right)
  = \frac{E}{2} \sigma_z + \Omega \sigma_x
  = \frac{E}{2} \sigma_z + \Omega (\sigma_+ +\sigma_-)
$$


In [2]:
N = 2 # Dimensión del espacio de Hilbert

psi0 = basis(N,0) # Vector |0>
psi1 = basis(N,1) # Vector |1>

In [3]:
print(psi0, psi1, psi1*psi1.dag())

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]] Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]] Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0. 0.]
 [0. 1.]]


In [4]:
# constant
E = 1.0
Omega = 1.0

In [5]:
#Hfun = lambda E, Omega: E * psi1*psi1.dag() + Omega * (psi0*psi1.dag() + psi1*psi0.dag())
def Hamiltonian(E, Omega):
    return (E * psi1*psi1.dag() + Omega * (psi0*psi1.dag() + psi1*psi0.dag()))
H = Hamiltonian(E, Omega)

In [6]:
psiini = basis(N,1)   # |1>
tlist = np.linspace(0,5,1000) # times

In [7]:
# 1. plot w.o. dissipation
expect_list = [psi0*psi0.dag(),psi1*psi1.dag()]
c_op_list = []

In [8]:
me = mesolve(H, psiini, tlist, c_op_list, expect_list)

/home/leopold/PycharmProjects/Master_thesis/.venv/lib/python3.12/site-packages/qutip/solver/solver_base.py:576: FutureWarning: e_ops will be keyword only from qutip 5.3 for all solver
  warnings.warn(


In [9]:
plt.plot(tlist, me.expect[0])#, label=r'state ${0}$')
plt.plot(tlist, me.expect[1])#, label=r'state ${1}$')
plt.xlabel(r'$t$')#  / \gamma
plt.ylabel(r'Population')
plt.legend(('state ${0}$','state ${1}$'))
figure_name = f"2_lvl_sys_without_decay_psiini=e_E={E:.2f}_Omega={Omega:.2f}.svg"
plt.savefig(os.path.join(output_dir, figure_name))
plt.show()

RuntimeError: latex was not able to process the following string:
b'lp'

Here is the full command invocation and its output:

latex -interaction=nonstopmode --halt-on-error --output-directory=tmprvd72r7o a28abde43143e87d75ec91fd5cd25754.tex

This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023/Debian) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(./a28abde43143e87d75ec91fd5cd25754.tex
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-01-22>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathpazo.sty)
(/usr/share/texlive/texmf-dist/tex/latex/type1cm/type1cm.sty)

! LaTeX Error: File `type1ec.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.9 \usepackage
               [utf8]{inputenc}^^M
No pages of output.
Transcript written on tmprvd72r7o/a28abde43143e87d75ec91fd5cd25754.log.




Error in callback <function _draw_all_if_interactive at 0x79e1dc2b0680> (for post_execute), with arguments args (),kwargs {}:


RuntimeError: latex was not able to process the following string:
b'lp'

Here is the full command invocation and its output:

latex -interaction=nonstopmode --halt-on-error --output-directory=tmppwx_yr07 a28abde43143e87d75ec91fd5cd25754.tex

This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023/Debian) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(./a28abde43143e87d75ec91fd5cd25754.tex
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-01-22>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathpazo.sty)
(/usr/share/texlive/texmf-dist/tex/latex/type1cm/type1cm.sty)

! LaTeX Error: File `type1ec.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.9 \usepackage
               [utf8]{inputenc}^^M
No pages of output.
Transcript written on tmppwx_yr07/a28abde43143e87d75ec91fd5cd25754.log.




RuntimeError: latex was not able to process the following string:
b'lp'

Here is the full command invocation and its output:

latex -interaction=nonstopmode --halt-on-error --output-directory=tmpw70y_opb a28abde43143e87d75ec91fd5cd25754.tex

This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023/Debian) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(./a28abde43143e87d75ec91fd5cd25754.tex
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-01-22>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathpazo.sty)
(/usr/share/texlive/texmf-dist/tex/latex/type1cm/type1cm.sty)

! LaTeX Error: File `type1ec.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.9 \usepackage
               [utf8]{inputenc}^^M
No pages of output.
Transcript written on tmpw70y_opb/a28abde43143e87d75ec91fd5cd25754.log.




<Figure size 800x600 with 1 Axes>

# Now with decay 
$$
c = \sqrt{\gamma} \sigma_-
$$


In [86]:
# constant
E = 1.
Gamma = .1
Omega = .0
n = 1.

In [87]:
# 1. plot w.o. dissipation
tlist = np.linspace(0,15,4000) # times
expect_list = [psi0*psi0.dag(),psi1*psi1.dag()]
c_op_list = [np.sqrt(Gamma * (1 + n)) * sigmap(), np.sqrt(Gamma * (n)) * sigmam()]

In [10]:
H = Hamiltonian(E, Omega)
me = mesolve(H, psiini, tlist, c_op_list, expect_list)

/home/leopold/PycharmProjects/Master_thesis/.venv/lib/python3.12/site-packages/qutip/solver/solver_base.py:576: FutureWarning: e_ops will be keyword only from qutip 5.3 for all solver
  warnings.warn(


In [89]:
plt.plot(tlist, me.expect[0])#, label=r'state ${0}$')
plt.plot(tlist, me.expect[1])#, label=r'state ${1}$')
plt.xlabel(r'$t$')
plt.ylabel(r'Population')
plt.legend(('state ${0}$','state ${1}$'))
figure_name = f"2_lvl_sys_with_decay_psiini=e_E={E:.2f}_Omega={Omega:.2f}_Gamma={Gamma:.2f}_n={n:.2f}.svg"
#plt.savefig(os.path.join(output_dir, figure_name))
plt.show()